import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { Helmet } from 'react-helmet-async';

const WhatIsAiAppBuilder = () => {
  const beforePrompt = `make a pricing table`;
  const afterPrompt = `**Task:**
Create a pricing table with three tiers: 'Free', 'Pro', and 'Team'.

**Brand Personality:**
Professional & Sleek

**Content Requirements:**
*   **Tier 1 (Free):** Price: "$0 / month", Description: "For individuals and hobbyists", Features: "10 Image Prompts/day", "Community Access", Button Text: "Start for Free".
*   **Tier 2 (Pro):** Price: "$10 / month", Description: "For professionals and power users", Features: "Unlimited Prompts", "Advanced Video & Audio Tools", "Priority Support", Button Text: "Upgrade to Pro".`;

  return (
    <>
      <Helmet>
        <title>What is an AI App Builder? A Simple Explanation</title>
        <meta name="description" content="Understand how AI app builders work and learn to create better prompts for tools like Replit AI and Lovable." />
        <meta name="keywords" content="AI app builder, what is Replit AI, no-code AI tools" />
      </Helmet>

      <div className="flex flex-col min-h-screen bg-background">
        <Navigation />

        <main className="flex-1 container py-16">
          <div className="max-w-3xl mx-auto">
            <Link to="/guides" className="inline-flex items-center text-primary hover:underline mb-8">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Guides
            </Link>

            <article className="prose prose-invert prose-lg max-w-none text-muted-foreground">
              <h1 className="text-4xl md:text-5xl font-heading font-bold text-foreground mb-8">
                What is an AI App Builder? A Simple Explanation
              </h1>

              <p>An AI App Builder is a tool that writes code for you based on a natural language description. Imagine describing a website or a component to a developer, but instead of a person, it's an AI that reads your instructions and builds it for you. The key to getting good results is providing a detailed, structured prompt that leaves nothing to guesswork.</p>

              <h3>The Power of a Structured Prompt</h3>
              <p>A simple, vague prompt will get you a simple, generic result. A detailed, structured prompt gets you exactly what you want, saving you hours of manual coding and refinement. Let's look at an example of building a pricing table.</p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 my-8">
                <div>
                  <h4 className="text-xl font-heading text-foreground">"Before" Prompt</h4>
                  <pre className="text-sm whitespace-pre-wrap font-mono bg-muted p-4 rounded-md h-full">{beforePrompt}</pre>
                </div>
                <div>
                  <h4 className="text-xl font-heading text-foreground">"After" Prompt (from PromptCraft)</h4>
                  <pre className="text-sm whitespace-pre-wrap font-mono bg-muted p-4 rounded-md h-full">{afterPrompt}</pre>
                </div>
              </div>

              <p>As you can see, the "after" prompt, generated by our tool, includes crucial details about the brand's personality, and specific content for each pricing tier, including features and button text. This level of detail ensures the AI has all the information it needs to build a component that fits your vision perfectly, right down to the styling.</p>

              <p>Ready to build something? Try the <Link to="/tools/app-builder" className="text-primary hover:underline">App Builder tool</Link> and see how easy it is to create detailed, structured prompts for your next project.</p>
            </article>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default WhatIsAiAppBuilder;
