// This file is automatically generated. Do not edit it directly.
// NOTE: Manually edited to fix project connection issue due to CLI environment constraints.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqbllsnxrkjrrihbdblw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxYmxsc254cmtqcnJpaGJkYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDQ1NzEsImV4cCI6MjA3MTQyMDU3MX0.XQVYbjoZITbDhTdBbPIZ7u5Nle_xyBgeCIoCz1w19Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});