// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mravufjdnunpfgyqluft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYXZ1ZmpkbnVucGZneXFsdWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTY5MDIsImV4cCI6MjA2ODc3MjkwMn0.mPfTBtuJBx-nzQKW3LYGJIj9tZn_LrPTgAgY7hxSWWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});